Move test into the build

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -26,29 +26,33 @@ jobs:
         run: |
           set -e
           cmake --build build -j
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: linux-build
-          path: build
-
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    container:
-      image: ghcr.io/${{ github.repository }}:latest
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: linux-build
-          path: build
-
-      - name: Test
-        run: |
-          set -e
           cd build
           export DISPLAY=:1
           Xvfb :1 -screen 0 1024x768x24 &
           ctest --output-on-failure -j
+
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: linux-build
+  #         path: build
+
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   container:
+  #     image: ghcr.io/${{ github.repository }}:latest
+  #   steps:
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: linux-build
+  #         path: build
+
+  #     - name: Test
+  #       run: |
+  #         set -e
+  #         cd build
+  #         export DISPLAY=:1
+  #         Xvfb :1 -screen 0 1024x768x24 &
+  #         ctest --output-on-failure -j
